version: '3.8'

services:
  receipt2budget-bot:
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
    build:
      context: .
    restart: unless-stopped
    env_file: ".env"
