version: '3.8'

services:
  telegram-receipt-bot:
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
    build:
      context: .
    container_name: receipt-bot
    restart: unless-stopped
    env_file: ".env"
#    command: ["uv", "run", "-m", "src.main"]
#    command: ["tail", "-f", "/dev/null"]
#
#    volumes:
#      - ./models:/app/models
